import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import pluginReact from "eslint-plugin-react";
import pluginUnusedImports from "eslint-plugin-unused-imports";
import pluginTailwindcss from "eslint-plugin-tailwindcss";
import { defineConfig } from "eslint/config";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

// The tailwindcss plugin can only parse plain CSS in its cssFiles setting,
// so classes defined in .scss files are extracted here and passed to
// no-custom-classname's whitelist instead
function scssClassnames() {
  const srcDir = path.join(projectRoot, "src");
  const names = new Set();
  for (const entry of fs.readdirSync(srcDir, { recursive: true })) {
    if (!entry.endsWith(".scss")) continue;
    const scss = fs.readFileSync(path.join(srcDir, entry), "utf8");
    for (const match of scss.matchAll(/\.([a-zA-Z_][\w-]*)/g)) {
      names.add(match[1]);
    }
  }
  return [...names];
}

export default defineConfig([
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    plugins: { js },
    ...js.configs.recommended,
  },
  {
    files: ["**/*.{js,mjs,cjs,ts,mts,cts,jsx,tsx}"],
    languageOptions: { globals: globals.browser },
  },
  tseslint.configs.recommended,
  pluginReact.configs.flat.recommended,
  {
    settings: { react: { version: "detect" } },
  },
  {
    // Ambient declaration files legitimately use triple-slash directives
    files: ["**/*.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },
  {
    // react-three-fiber JSX elements take three.js properties (args,
    // intensity, decay, ...) that the DOM-oriented rule doesn't know
    files: ["src/space3d/**/*.{ts,tsx}"],
    rules: {
      "react/no-unknown-property": "off",
    },
  },
  ...pluginTailwindcss.configs["flat/recommended"],
  {
    settings: {
      tailwindcss: {
        // Absolute path — the plugin resolves the tailwindcss package
        // relative to this file's directory
        config: new URL("./tailwind.config.js", import.meta.url).pathname,
        // Classname-building helpers whose string arguments should be linted
        callees: ["cn", "clsx", "classnames", "cva", "twMerge"],
        // Classes defined in these stylesheets are considered valid, so
        // no-custom-classname only flags truly undefined classnames
        cssFiles: ["src/**/*.css"],
        whitelist: scssClassnames(),
      },
    },
    rules: {
      // Flag classnames that aren't generated by the Tailwind config —
      // catches typos like "felx" and stale classes after theme changes
      "tailwindcss/no-custom-classname": "error",
      // Prefer m-4 over mt-4 mb-4 ml-4 mr-4, size-4 over w-4 h-4, etc.
      "tailwindcss/enforces-shorthand": "error",
      // e.g. -top-[5px] instead of top-[-5px]
      "tailwindcss/enforces-negative-arbitrary-values": "error",
      // Prefer built-in scale values over arbitrary ones (w-4 vs w-[16px])
      "tailwindcss/no-unnecessary-arbitrary-value": "error",
      // Reject deprecated Tailwind v2 classnames (flex-grow, bg-opacity-*, ...)
      "tailwindcss/migration-from-tailwind-2": "error",
      "tailwindcss/no-contradicting-classname": "error",
    },
  },
  {
    files: ["**/*.{js,jsx,ts,tsx}"],
    plugins: {
      "unused-imports": pluginUnusedImports,
    },
    rules: {
      "no-unused-vars": "off",
      "unused-imports/no-unused-imports": "error",
      "unused-imports/no-unused-vars": [
        "error",
        {
          vars: "all",
          varsIgnorePattern: "^_",
          args: "after-used",
          argsIgnorePattern: "^_",
        },
      ],
    },
  },
]);
